spring:
  datasource:
    url: jdbc:mysql://localhost:3306/detections?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: camilo
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
      minimum-idle: 2
  
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: false
        format_sql: false
        cache:
          use_second_level_cache: false
          use_query_cache: false
  
  mvc:
    async:
      request-timeout: 20000
      
server:
  port: 8080
  tomcat:
    threads:
      max: 10
    connection-timeout: 20000

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO
    com.example.demo: DEBUG
    org.apache.tomcat: DEBUG
    org.apache.coyote: DEBUG